[[docs]]
  name = "Prólogo"
  weight = 10
  identifier = "prologo"
  url = "/docs/prologo/"

[[docs]]
  name = "Esteganografía"
  weight = 20
  identifier = "stego"
  url = "/docs/stego/"

[[docs]]
  name = "Criptografía Moderna"
  weight = 30
  identifier = "cripto-moderna"
  url = "/docs/cripto-moderna/"

[[docs]]
  name = "Aplicaciones Web"
  weight = 40
  identifier = "apps-web"
  url = "/docs/apps-web/"


[[docs]]
  name = "Análisis Forense"
  weight = 50
  identifier = "forense"
  url = "/docs/forense/"

[[docs]]
  name = "Ingeniería Reversa"
  weight = 60
  identifier = "reversa"
  url = "/docs/reversa/"

[[docs]]
  name = "Pwning"
  weight = 70
  identifier = "pwning"
  url = "/docs/pwning/"

[[docs]]
  name = "OSINT"
  weight = 80
  identifier = "osint"
  url = "/docs/osint/"

[[docs]]
  name = "Anexos"
  weight = 90
  identifier = "anexos"
  url = "/docs/anexos/"


[[main]]
  name = "Videos"
  url = "/blog/"
  weight = 10

[[main]]
  name = "Apunte"
  url = "/docs/prologo/intro"
  weight = 20

  [[main]]
  name = "Writeups"
  url = "/writeups/misc/registro_htb"
  weight = 25

[[main]]
  name = "Acerca"
  url = "/acerca"
  weight = 30

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/cc5325/apunte"
  weight = 20
